# Generated by Django 4.0.1 on 2022-01-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='订单id'),
        ),
    ]
